defaults:
  - agent_config: dmpo   
  - trainer_config: trainer_config         
  - wandb_config: diffusion_wandb 
  - _self_ 


header: "import tonic.torch"
agent: "tonic.torch.agents.DMPO()"
environment: 'tonic.environments.Gym("Pendulum-v1")'
test_environment: null
trainer: "tonic.Trainer()"
before_training: ""
after_training: ""
parallel: 1
sequential: 1
seed: 0
name: "DMPO-X"
environment_name: null
checkpoint: "last"
path: ""

hydra:
  mode: MULTIRUN
  sweeper:
    combination_sweeper:
      params:
        # When actor_squash=true, run with action_scale=2 and action_scale=1
        # For both seed values (0,1)
        - agent_config.agent_config.model.actor_squash: true
          agent_config.agent_config.model.action_scale: 2
          seed: 0,1
        - agent_config.agent_config.model.actor_squash: true
          agent_config.agent_config.model.action_scale: 1
          seed: 0,1
        # When actor_squash=false, run only with action_scale=1
        # For both seed values (0,1)
        - agent_config.agent_config.model.actor_squash: false
          agent_config.agent_config.model.action_scale: 1
          seed: 0,1