defaults:
  - agent_config: dmpo   
  - trainer_config: trainer_config         
  - wandb_config: diffusion_wandb 
  - _self_ 



header: "import tonic.torch"
agent: "tonic.torch.agents.DMPO()"
environment: 'tonic.environments.Gym("Pendulum-v1")' #'tonic.environments.ControlSuite("fish-swim")'
test_environment: null
trainer: "tonic.Trainer()"
before_training: ""
after_training: ""
parallel: 1
sequential: 1
seed: 0
name: "DMPO-X"
environment_name: null
checkpoint: "last"
path: ""

# Added Hydra multirun configuration
hydra:
  mode: MULTIRUN 
  sweeper:
    params:
      seed: 0,1
      "agent_config.agent_config.replay_updater.steps_between_batches": 5,15,30
