# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  run:
    dir: ./outputs/training/${now:%Y-%m-%d}/${name}
  sweep:
    dir: ./outputs/training/${now:%Y-%m-%d}
    subdir: ${name}/seed_${seed}
  launcher:
    partition: "dev_cpu_il"        
    timeout_min: 30
    # Remove GPU-related fields like `gres`, `mem_per_gpu`
    mem_per_cpu: 12000               # MB per CPU core
    

